### PR TITLE
Validate changelog in prepublishOnly

### PR DESCRIPTION
**Pull request by rekmarks**
We should probably use the thing in the thing.

### CODE REVIEW

**Review by Gudahtt — CHANGES_REQUESTED** [review]
I'm not sure this is a good idea. The `--rc` flag would mean this would _fail_ after the tag was created, as the tag wouldn't exist in the RC phase. Whereas this command might be run before or after the tag is created (mostly likely after).

Definitely worth adding to CI! But maybe not to `prepublishOnly`

**Comment by rekmarks** [comment]
Guess we'll save it for when we're only publishing in CI 😎

**Comment by Gudahtt** [comment]
Oh I meant on normal CI. Like, alongside unit tests and the linter.

**Comment by Gudahtt** [comment]
e.g. https://github.com/MetaMask/metamask-extension/blob/develop/.circleci/config.yml#L289

**Pull request closed without merging**
